name: Bundle

on:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Build
#       run: cargo build --verbose
    - name: Make Bundle
      run: ./scripts/make-bundle.sh
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ git_hash }}
        release_name: Release ${{ git_hash }}
        body: |
          Changes in this Release
          - Latest Bundle
        draft: false
        prerelease: false

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./bundle/bundle.tar.gz
        asset_name: bundle.tar.gz
        asset_content_type: application/zip
